apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres-claim1
  name: postgres-claim1
  namespace: moaitime
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres-data
  name: postgres-data
  namespace: moaitime
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: moaitime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
      namespace: moaitime
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: database
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: user
          image: postgres:15.4
          name: moaitime-postgres
          ports:
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
            - mountPath: /docker-entrypoint-initdb.d/init-dbs.sh
              name: postgres-claim1
      restartPolicy: Always
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
        - name: postgres-claim1
          persistentVolumeClaim:
            claimName: postgres-claim1
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: moaitime
spec:
  ports:
    - name: '5432'
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
status:
  loadBalancer: {}
