apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: redis-data
  name: redis-data
  namespace: moaitime
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
  namespace: moaitime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
      namespace: moaitime
    spec:
      containers:
        - image: redis:7.2.0
          name: moaitime-redis
          ports:
            - containerPort: 6379
              hostPort: 6379
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: redis-data
      restartPolicy: Always
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: moaitime
spec:
  ports:
    - name: '6379'
      port: 6379
      targetPort: 6379
  selector:
    app: redis
status:
  loadBalancer: {}
