version: '3.8'

# Here we will have all the services that are needed for the project to run

name: moaitime

services:
  postgres:
    container_name: moaitime_postgres
    image: postgres:15.4
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    shm_size: 8gb
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init-dbs.sh:/docker-entrypoint-initdb.d/init-dbs.sh
    ports:
      - 5432:5432
    networks:
      - moaitime-network

  redis:
    container_name: moaitime_redis
    image: redis:7.2.0
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    networks:
      - moaitime-network

networks:
  moaitime-network:
    name: moaitime_network
    driver: bridge

volumes:
  postgres-data:
  redis-data:
