version: '3.8'

# Here we will have all the services that are needed for the project to run

services:
  postgres:
    container_name: moaitime_postgres
    image: postgres:15.4
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    shm_size: 8gb
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init-dbs.sh:/docker-entrypoint-initdb.d/init-dbs.sh
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    networks:
      - moaitime-network

  redis:
    container_name: moaitime_redis
    image: redis:7.2.0
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - ${REDIS_PORT:-6379}:6379
    networks:
      - moaitime-network

  rabbitmq:
    container_name: moaitime_rabbitmq
    image: rabbitmq:3.12.12-management
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
    ports:
      - ${RABBITMQ_PORT:-5672}:5672
      - ${RABBITMQ_UI_PORT:-15672}:15672
    networks:
      - moaitime-network

  minio:
    container_name: moaitime_minio
    image: docker.io/bitnami/minio:2023.12.23
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DEFAULT_BUCKETS=user-avatars,user-data-exports,database-backups
    volumes:
      - minio-data:/data
    ports:
      - ${MINIO_PORT:-9000}:9000
      - ${MINIO_UI_PORT:-9001}:9001
    networks:
      - moaitime-network

networks:
  moaitime-network:
    name: moaitime_network
    driver: bridge

volumes:
  postgres-data:
  redis-data:
  rabbitmq-data:
  minio-data:
