version: '3.8'

# Here we have all the services that we need to deploy our application

services:
  portainer:
    # Username is "admin" and password is "password"
    container_name: moaitime_portainer
    image: portainer/portainer-ce:2.20.1
    command: --admin-password '$$2y$$05$$Gi2cvNgIzh2cwEKV9gd0oOTn8Ju8alEX0.963i/poGO340XYS1JdO' # The password is "password"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9443:9443
    networks:
      - moaitime-network

#  docker-registry:
#    container_name: moaitime_docker_registry
#    image: registry:2.8.3
#    restart: unless-stopped
#    deploy:
#      resources:
#        limits:
#          cpus: '2'
#          memory: 4G
#    volumes:
#      - docker-registry-data:/var/lib/registry
#    ports:
#      - 5050:5000 # Need to set to 5050 because 5000 is already in use by the local docker desktop registry, so we can not really run both at the same time
#    networks:
#      - moaitime-network

networks:
  moaitime-network:
    name: moaitime_network
    driver: bridge

volumes:
  portainer-data:
  docker-registry-data:
